spring.application.name=journal App

#spring.data.mongodb.username=myjournaluser
#spring.data.mongodb.password=mypassword

spring.data.mongodb.uri=your mongoDB uri
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true