spring.application.name=journal App

server.port= ${SERVER_PORT}

#-----SPRING SECURITY basic config-----
#spring.data.mongodb.username=myjournaluser
#spring.data.mongodb.password=mypassword

#-----MONGO DB config-----
spring.data.mongodb.uri= ${MONGO_DB_URI}
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true

#-----SPRING PROFILES-----
#spring.profiles.active=dev

#-----LOGGING-----
#logging.level.com.edigest.journalApp = DEBUG

#-----Mail Sender Config-----
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= ${JAVA_EMAIL}
spring.mail.password= ${JAVA_EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true